version: '3.8'

services:
  api-test:
    build: .
    container_name: scriptflow_api_test
    ports:
      - "8000:8000"
    env_file:
      - .env.test
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: scriptflow_test_net
