"""add split rules and extend storage fields

Revision ID: 268402db6fea
Revises: add_skill_template_fields
Create Date: 2026-02-04 18:53:01.003117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '268402db6fea'
down_revision: Union[str, None] = 'add_skill_template_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_skill_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('custom_parameters', sa.JSON(), nullable=True),
    sa.Column('execution_order', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consistency_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('check_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('results', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consistency_checks_batch_id'), 'consistency_checks', ['batch_id'], unique=False)
    op.create_index(op.f('ix_consistency_checks_check_type'), 'consistency_checks', ['check_type'], unique=False)
    op.create_index(op.f('ix_consistency_checks_project_id'), 'consistency_checks', ['project_id'], unique=False)
    op.create_index(op.f('ix_consistency_checks_status'), 'consistency_checks', ['status'], unique=False)
    op.drop_index('idx_agent_definitions_category', table_name='agent_definitions')
    op.drop_index('idx_agent_definitions_name', table_name='agent_definitions')
    op.drop_index('idx_agent_definitions_user_id', table_name='agent_definitions')
    op.alter_column('agent_executions', 'agent_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('idx_agent_executions_agent_id', table_name='agent_executions')
    op.drop_index('idx_agent_executions_created_at', table_name='agent_executions')
    op.drop_index('idx_agent_executions_pipeline_id', table_name='agent_executions')
    op.create_foreign_key(None, 'agent_executions', 'agent_definitions', ['agent_id'], ['id'], ondelete='CASCADE')
    op.alter_column('agent_workflow_executions', 'agent_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('idx_workflow_agent_id', table_name='agent_workflow_executions')
    op.drop_index('idx_workflow_execution_id', table_name='agent_workflow_executions')
    op.create_foreign_key(None, 'agent_workflow_executions', 'agent_executions', ['execution_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'agent_workflow_executions', 'agent_definitions', ['agent_id'], ['id'], ondelete='CASCADE')
    op.add_column('batches', sa.Column('ai_processed', sa.Boolean(), nullable=True))
    op.add_column('batches', sa.Column('context_size', sa.Integer(), nullable=True))
    op.alter_column('billing_records', 'balance_after',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('idx_billing_records_created_at', table_name='billing_records')
    op.drop_index('idx_billing_records_type', table_name='billing_records')
    op.drop_index('idx_billing_records_user_id', table_name='billing_records')
    op.create_index(op.f('ix_billing_records_reference_id'), 'billing_records', ['reference_id'], unique=False)
    op.create_index(op.f('ix_billing_records_type'), 'billing_records', ['type'], unique=False)
    op.create_index(op.f('ix_billing_records_user_id'), 'billing_records', ['user_id'], unique=False)
    op.create_foreign_key(None, 'billing_records', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('chapters', sa.Column('txt_file_path', sa.String(length=500), nullable=True))
    op.add_column('chapters', sa.Column('txt_file_size', sa.Integer(), nullable=True))
    op.add_column('chapters', sa.Column('skill_processed', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('idx_pipeline_node_agents_pipeline', table_name='pipeline_node_agents')
    op.create_foreign_key(None, 'pipeline_node_agents', 'agent_definitions', ['agent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pipeline_node_agents', 'pipelines', ['pipeline_id'], ['id'], ondelete='CASCADE')
    op.add_column('plot_breakdowns', sa.Column('consistency_score', sa.Integer(), nullable=True))
    op.add_column('plot_breakdowns', sa.Column('consistency_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('subscriptions', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('idx_subscriptions_status', table_name='subscriptions')
    op.drop_index('idx_subscriptions_user_id', table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_expires_at'), 'subscriptions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_tier'), 'subscriptions', ['tier'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_users_tier', table_name='users')
    op.create_index(op.f('ix_users_tier'), 'users', ['tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tier'), table_name='users')
    op.create_index('idx_users_tier', 'users', ['tier'], unique=False)
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_tier'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_expires_at'), table_name='subscriptions')
    op.create_index('idx_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    op.create_index('idx_subscriptions_status', 'subscriptions', ['status'], unique=False)
    op.alter_column('subscriptions', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('plot_breakdowns', 'consistency_results')
    op.drop_column('plot_breakdowns', 'consistency_score')
    op.drop_constraint(None, 'pipeline_node_agents', type_='foreignkey')
    op.drop_constraint(None, 'pipeline_node_agents', type_='foreignkey')
    op.create_index('idx_pipeline_node_agents_pipeline', 'pipeline_node_agents', ['pipeline_id', 'node_id'], unique=False)
    op.drop_column('chapters', 'skill_processed')
    op.drop_column('chapters', 'txt_file_size')
    op.drop_column('chapters', 'txt_file_path')
    op.drop_constraint(None, 'billing_records', type_='foreignkey')
    op.drop_index(op.f('ix_billing_records_user_id'), table_name='billing_records')
    op.drop_index(op.f('ix_billing_records_type'), table_name='billing_records')
    op.drop_index(op.f('ix_billing_records_reference_id'), table_name='billing_records')
    op.create_index('idx_billing_records_user_id', 'billing_records', ['user_id'], unique=False)
    op.create_index('idx_billing_records_type', 'billing_records', ['type'], unique=False)
    op.create_index('idx_billing_records_created_at', 'billing_records', ['created_at'], unique=False)
    op.alter_column('billing_records', 'balance_after',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('batches', 'context_size')
    op.drop_column('batches', 'ai_processed')
    op.drop_constraint(None, 'agent_workflow_executions', type_='foreignkey')
    op.drop_constraint(None, 'agent_workflow_executions', type_='foreignkey')
    op.create_index('idx_workflow_execution_id', 'agent_workflow_executions', ['execution_id'], unique=False)
    op.create_index('idx_workflow_agent_id', 'agent_workflow_executions', ['agent_id'], unique=False)
    op.alter_column('agent_workflow_executions', 'agent_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'agent_executions', type_='foreignkey')
    op.create_index('idx_agent_executions_pipeline_id', 'agent_executions', ['pipeline_id'], unique=False)
    op.create_index('idx_agent_executions_created_at', 'agent_executions', ['created_at'], unique=False)
    op.create_index('idx_agent_executions_agent_id', 'agent_executions', ['agent_id'], unique=False)
    op.alter_column('agent_executions', 'agent_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('idx_agent_definitions_user_id', 'agent_definitions', ['user_id'], unique=False)
    op.create_index('idx_agent_definitions_name', 'agent_definitions', ['name'], unique=False)
    op.create_index('idx_agent_definitions_category', 'agent_definitions', ['category'], unique=False)
    op.drop_index(op.f('ix_consistency_checks_status'), table_name='consistency_checks')
    op.drop_index(op.f('ix_consistency_checks_project_id'), table_name='consistency_checks')
    op.drop_index(op.f('ix_consistency_checks_check_type'), table_name='consistency_checks')
    op.drop_index(op.f('ix_consistency_checks_batch_id'), table_name='consistency_checks')
    op.drop_table('consistency_checks')
    op.drop_table('user_skill_configs')
    # ### end Alembic commands ###
