"""Add ai_configurations table

Revision ID: 4b9418e09e5a
Revises: 7bfc52e44aa3
Create Date: 2026-02-08 00:10:14.597172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b9418e09e5a'
down_revision: Union[str, None] = '7bfc52e44aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_configurations_key'), 'ai_configurations', ['key'], unique=True)
    op.add_column('plot_breakdowns', sa.Column('qa_status', sa.String(length=50), nullable=True))
    op.add_column('plot_breakdowns', sa.Column('qa_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('plot_breakdowns', sa.Column('used_adapt_method_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_plot_breakdowns_qa_status'), 'plot_breakdowns', ['qa_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plot_breakdowns_qa_status'), table_name='plot_breakdowns')
    op.drop_column('plot_breakdowns', 'used_adapt_method_id')
    op.drop_column('plot_breakdowns', 'qa_report')
    op.drop_column('plot_breakdowns', 'qa_status')
    op.drop_index(op.f('ix_ai_configurations_key'), table_name='ai_configurations')
    op.drop_table('ai_configurations')
    # ### end Alembic commands ###
