"""add_announcements_tables

Revision ID: 5420f22114d0
Revises: add_api_log_body_fields_v2
Create Date: 2026-02-25 23:31:28.189835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5420f22114d0'
down_revision: Union[str, None] = 'add_api_log_body_fields_v2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='通知标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='通知内容（支持 Markdown）'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='优先级'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='通知类型'),
    sa.Column('is_published', sa.Boolean(), nullable=False, comment='是否已发布'),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='发布时间'),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='过期时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='创建者用户ID'),
    sa.Column('target_user_id', sa.UUID(), nullable=True, comment='目标用户ID（NULL表示全局通知）'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_expires_at'), 'announcements', ['expires_at'], unique=False)
    op.create_index(op.f('ix_announcements_is_deleted'), 'announcements', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_announcements_is_published'), 'announcements', ['is_published'], unique=False)
    op.create_index(op.f('ix_announcements_priority'), 'announcements', ['priority'], unique=False)
    op.create_index(op.f('ix_announcements_target_user_id'), 'announcements', ['target_user_id'], unique=False)
    op.create_index(op.f('ix_announcements_type'), 'announcements', ['type'], unique=False)

    op.create_table('announcement_reads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('announcement_id', sa.UUID(), nullable=False, comment='通知ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('read_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='已读时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_announcement_user', 'announcement_reads', ['announcement_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_announcement_reads_announcement_id'), 'announcement_reads', ['announcement_id'], unique=False)
    op.create_index(op.f('ix_announcement_reads_user_id'), 'announcement_reads', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_announcement_reads_user_id'), table_name='announcement_reads')
    op.drop_index(op.f('ix_announcement_reads_announcement_id'), table_name='announcement_reads')
    op.drop_index('idx_announcement_user', table_name='announcement_reads')
    op.drop_table('announcement_reads')

    op.drop_index(op.f('ix_announcements_type'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_target_user_id'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_priority'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_is_published'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_is_deleted'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_expires_at'), table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###
