"""add_script_status_and_qa_fields

Revision ID: 6646e9d6eb5e
Revises: d4da2e01cfa5
Create Date: 2026-02-22 00:10:49.484432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6646e9d6eb5e'
down_revision: Union[str, None] = 'd4da2e01cfa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_llm_call_logs_created_at', table_name='llm_call_logs')
    op.drop_index('ix_llm_call_logs_model_name', table_name='llm_call_logs')
    op.drop_index('ix_llm_call_logs_provider', table_name='llm_call_logs')
    op.drop_index('ix_llm_call_logs_skill_name', table_name='llm_call_logs')
    op.drop_index('ix_llm_call_logs_status', table_name='llm_call_logs')
    op.drop_index('ix_llm_call_logs_task_id', table_name='llm_call_logs')
    op.drop_index('ix_llm_call_logs_user_id', table_name='llm_call_logs')
    op.drop_table('llm_call_logs')
    op.drop_index('ix_api_logs_created_at', table_name='api_logs')
    op.drop_index('ix_api_logs_path', table_name='api_logs')
    op.drop_index('ix_api_logs_status_code', table_name='api_logs')
    op.drop_index('ix_api_logs_user_id', table_name='api_logs')
    op.drop_table('api_logs')
    op.drop_index('ix_system_configs_key', table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_column('plot_breakdowns', 'plot_points_raw')
    op.add_column('scripts', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('scripts', sa.Column('qa_status', sa.String(length=50), nullable=True))
    op.add_column('scripts', sa.Column('qa_score', sa.Integer(), nullable=True))
    op.add_column('scripts', sa.Column('qa_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('scripts', sa.Column('approved_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('simple_agents', 'workflow',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('skills', 'input_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('skills', 'model_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('skills', 'example_input',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('skills', 'example_output',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_column('skills', 'input_variables')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('input_variables', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('skills', 'example_output',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('skills', 'example_input',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('skills', 'model_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('skills', 'input_schema',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('simple_agents', 'workflow',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('scripts', 'approved_at')
    op.drop_column('scripts', 'qa_report')
    op.drop_column('scripts', 'qa_score')
    op.drop_column('scripts', 'qa_status')
    op.drop_column('scripts', 'status')
    op.add_column('plot_breakdowns', sa.Column('plot_points_raw', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table('system_configs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='system_configs_pkey')
    )
    op.create_index('ix_system_configs_key', 'system_configs', ['key'], unique=True)
    op.create_table('api_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('query_params', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_ip', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('response_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('request_body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('response_body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='api_logs_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='api_logs_pkey')
    )
    op.create_index('ix_api_logs_user_id', 'api_logs', ['user_id'], unique=False)
    op.create_index('ix_api_logs_status_code', 'api_logs', ['status_code'], unique=False)
    op.create_index('ix_api_logs_path', 'api_logs', ['path'], unique=False)
    op.create_index('ix_api_logs_created_at', 'api_logs', ['created_at'], unique=False)
    op.create_table('llm_call_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('skill_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('stage', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('prompt_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('response_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'success'::character varying"), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='llm_call_logs_project_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['ai_tasks.id'], name='llm_call_logs_task_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='llm_call_logs_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='llm_call_logs_pkey')
    )
    op.create_index('ix_llm_call_logs_user_id', 'llm_call_logs', ['user_id'], unique=False)
    op.create_index('ix_llm_call_logs_task_id', 'llm_call_logs', ['task_id'], unique=False)
    op.create_index('ix_llm_call_logs_status', 'llm_call_logs', ['status'], unique=False)
    op.create_index('ix_llm_call_logs_skill_name', 'llm_call_logs', ['skill_name'], unique=False)
    op.create_index('ix_llm_call_logs_provider', 'llm_call_logs', ['provider'], unique=False)
    op.create_index('ix_llm_call_logs_model_name', 'llm_call_logs', ['model_name'], unique=False)
    op.create_index('ix_llm_call_logs_created_at', 'llm_call_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###
