"""add_user_id_and_category_to_ai_configurations

Revision ID: afd71162fd22
Revises: 4b9418e09e5a
Create Date: 2026-02-08 00:58:42.148558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afd71162fd22'
down_revision: Union[str, None] = '4b9418e09e5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_configurations', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('ai_configurations', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('ai_configurations', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_index('ix_ai_configurations_key', table_name='ai_configurations')
    op.create_index(op.f('ix_ai_configurations_key'), 'ai_configurations', ['key'], unique=False)
    op.create_unique_constraint('_user_key_uc', 'ai_configurations', ['user_id', 'key'])
    op.create_index(op.f('ix_ai_configurations_category'), 'ai_configurations', ['category'], unique=False)
    op.create_index(op.f('ix_ai_configurations_user_id'), 'ai_configurations', ['user_id'], unique=False)
    op.create_foreign_key(None, 'ai_configurations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_configurations', type_='foreignkey')
    op.drop_index(op.f('ix_ai_configurations_user_id'), table_name='ai_configurations')
    op.drop_index(op.f('ix_ai_configurations_category'), table_name='ai_configurations')
    op.drop_constraint('_user_key_uc', 'ai_configurations', type_='unique')
    op.drop_index(op.f('ix_ai_configurations_key'), table_name='ai_configurations')
    op.create_index('ix_ai_configurations_key', 'ai_configurations', ['key'], unique=True)
    op.drop_column('ai_configurations', 'is_active')
    op.drop_column('ai_configurations', 'category')
    op.drop_column('ai_configurations', 'user_id')
    # ### end Alembic commands ###
