"""add_model_management_tables

Revision ID: eece6c8e3bad
Revises: afd71162fd22
Create Date: 2026-02-08 17:05:32.774506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eece6c8e3bad'
down_revision: Union[str, None] = 'afd71162fd22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_model_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_key', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('api_endpoint', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_system_default', sa.Boolean(), nullable=True),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_model_providers_is_enabled'), 'ai_model_providers', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_ai_model_providers_provider_key'), 'ai_model_providers', ['provider_key'], unique=True)
    op.create_table('system_model_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('value_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_editable', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_model_config_config_key'), 'system_model_config', ['config_key'], unique=True)
    op.create_table('ai_model_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('credential_name', sa.String(length=100), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('api_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_system_default', sa.Boolean(), nullable=True),
    sa.Column('quota_limit', sa.Integer(), nullable=True),
    sa.Column('quota_used', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_model_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_model_credentials_is_active'), 'ai_model_credentials', ['is_active'], unique=False)
    op.create_index(op.f('ix_ai_model_credentials_provider_id'), 'ai_model_credentials', ['provider_id'], unique=False)
    op.create_table('ai_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('model_key', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('max_input_tokens', sa.Integer(), nullable=True),
    sa.Column('max_output_tokens', sa.Integer(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('temperature_default', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('supports_streaming', sa.Boolean(), nullable=True),
    sa.Column('supports_function_calling', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_model_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'model_key', name='_provider_model_uc')
    )
    op.create_index(op.f('ix_ai_models_is_default'), 'ai_models', ['is_default'], unique=False)
    op.create_index(op.f('ix_ai_models_is_enabled'), 'ai_models', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_ai_models_provider_id'), 'ai_models', ['provider_id'], unique=False)
    op.create_table('ai_model_pricing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('input_credits_per_1k_tokens', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('output_credits_per_1k_tokens', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('min_credits_per_request', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('effective_from', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('effective_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_model_pricing_is_active'), 'ai_model_pricing', ['is_active'], unique=False)
    op.create_index(op.f('ix_ai_model_pricing_model_id'), 'ai_model_pricing', ['model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_model_pricing_model_id'), table_name='ai_model_pricing')
    op.drop_index(op.f('ix_ai_model_pricing_is_active'), table_name='ai_model_pricing')
    op.drop_table('ai_model_pricing')
    op.drop_index(op.f('ix_ai_models_provider_id'), table_name='ai_models')
    op.drop_index(op.f('ix_ai_models_is_enabled'), table_name='ai_models')
    op.drop_index(op.f('ix_ai_models_is_default'), table_name='ai_models')
    op.drop_table('ai_models')
    op.drop_index(op.f('ix_ai_model_credentials_provider_id'), table_name='ai_model_credentials')
    op.drop_index(op.f('ix_ai_model_credentials_is_active'), table_name='ai_model_credentials')
    op.drop_table('ai_model_credentials')
    op.drop_index(op.f('ix_system_model_config_config_key'), table_name='system_model_config')
    op.drop_table('system_model_config')
    op.drop_index(op.f('ix_ai_model_providers_provider_key'), table_name='ai_model_providers')
    op.drop_index(op.f('ix_ai_model_providers_is_enabled'), table_name='ai_model_providers')
    op.drop_table('ai_model_providers')
    # ### end Alembic commands ###
